#! /bin/sh
sxhkd &
polybar example &
xcompmgr &
pulseaudio & 
wal -i "/home/jkaspar/Pictures/Wallpapers" & 
mopidy --config ~/.config/mopidy/mopidy.conf & 
# nohup mopidy &;mkfifo /tmp/mpd.fifo;while :; do yes $’\n’ | nc -lu 127.0.0.1 5555 > /tmp/mpd.fifo; done &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Connman-gtk state=floating center=on
