#! /bin/sh
sxhkd &
./.config/polybar/launch.sh & 
compton  &
pulseaudio & 
feh --bg-fill ~/Pictures/background.jpg &  
./.config/bspwm/launch_mopidy.sh & 
# nohup mopidy &;mkfifo /tmp/mpd.fifo;while :; do yes $’\n’ | nc -lu 127.0.0.1 5555 > /tmp/mpd.fifo; done &

bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap           7 

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Connman-gtk state=floating center=on

bspc monitor eDP-1 -d web code term music mail
query='bspc query -M'

i=6
read -a monitors <<<$query
if[[${#monitors[@]} > 1 ]]; then
    for monitor in ${monitors[@]}; do
        bspc monitor $monitor -d $i
        let i++
    done
fi
