#! /bin/sh
sxhkd &
polybar left &
polybar center & 
polybar right & 
compton  &
pulseaudio & 
wal -i "/home/jkaspar/Pictures/Wallpapers" & 
mopidy --config ~/.config/mopidy/mopidy.conf & 
# nohup mopidy &;mkfifo /tmp/mpd.fifo;while :; do yes $’\n’ | nc -lu 127.0.0.1 5555 > /tmp/mpd.fifo; done &

bspc config focus_follows_pointer true
bspc monitor eDP-1 -d I II III IV V

query='bspc query -M'

i=6
read -a monitors <<<$query
if[[${#monitors[@]} > 1 ]]; then
    for monitor in ${monitors[@]}; do
        bspc monitor $monitor -d $i
        let i++
    done
fi 
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Connman-gtk state=floating center=on
